# Stage 1: Build the Angular application
FROM node:22.22.3-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build 

# Stage 2: Serve the application with Nginx
FROM nginx:alpine
COPY --from=build /app/dist/healthcare-portal/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
