# Stage 2: Serve the application with Nginx
FROM nginx:alpine

# Copy your locally built Angular dist folder into Nginx
COPY dist/healthcare-portal /usr/share/nginx/html

# Copy your Nginx config (adjust path if needed)
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
