# Stage 1: Build the Angular application
FROM node:22.22.3-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build 

# Stage 2: Serve the application with Nginx

#COPY --from=build /app/dist/healthcare-portal/browser /usr/share/nginx/html

FROM nginx:alpine
COPY dist/healthcare-portal /usr/share/nginx/html
COPY ../nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
